[theme]
primaryColor = "#007A6E"
backgroundColor = "#F4F8F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#172321"
font = "sans serif"

[runner]
fastReruns = true

[server]
headless = true

[client]
showErrorDetails = false
